# Generated by Django 2.2.3 on 2019-07-12 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='recommended',
            field=models.BooleanField(default=False, verbose_name='Recommended'),
        ),
    ]
