# Generated by Django 2.2.3 on 2019-07-12 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190712_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='picture',
            field=models.ImageField(upload_to='media/picture', verbose_name='Picture from the movie'),
        ),
    ]
